export const theme = {
  cream: "#f3f4f6",
  sand: "#c4b5fd",
  caramel: "#67e8f9",
  cocoa: "#334155",
  sage: "#86efac",
  moss: "#4ade80",
  rust: "#fbbf24",
  rose: "#fb7185",
  ink: "#d7e0ea",
  muted: "#94a3b8",
  faint: "#64748b",
  panel: "#18212f",
  user: "#c4b5fd",
  assistant: "#67e8f9",
  tool: "#fbbf24",
  worker: "#f0abfc",
} as const;

export const glyph = {
  brand: "◈",
  user: "›",
  assistant: "✦",
  tool: "↳",
  worker: "◇",
  success: "✓",
  error: "×",
  pending: "○",
  active: "◉",
  done: "●",
} as const;
